"""add_masjid_reviews

Revision ID: 05e64234de03
Revises: a82193150245
Create Date: 2026-04-25 20:29:25.783210

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "05e64234de03"
down_revision: Union[str, Sequence[str], None] = "a82193150245"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "masjid_reviews",
        sa.Column("review_id", sa.UUID(), nullable=False),
        sa.Column("masjid_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("reviewer_display_name", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("rating BETWEEN 1 AND 5", name="ck_masjid_reviews_rating"),
        sa.ForeignKeyConstraint(
            ["masjid_id"], ["masjids.masjid_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("review_id"),
        sa.UniqueConstraint("user_id", "masjid_id", name="uq_masjid_review_user"),
    )
    op.create_index(
        "idx_masjid_reviews_masjid", "masjid_reviews", ["masjid_id"], unique=False
    )
    op.create_index(
        op.f("ix_masjid_reviews_user_id"), "masjid_reviews", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_masjid_reviews_user_id"), table_name="masjid_reviews")
    op.drop_index("idx_masjid_reviews_masjid", table_name="masjid_reviews")
    op.drop_table("masjid_reviews")
    # ### end Alembic commands ###
