"""add_user_masjid_follows

Revision ID: 2535dc4d3f25
Revises: 9ac5759232e8
Create Date: 2026-04-25 19:28:57.774488

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2535dc4d3f25"
down_revision: Union[str, Sequence[str], None] = "9ac5759232e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_masjid_follows",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("masjid_id", sa.UUID(), nullable=False),
        sa.Column(
            "followed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["masjid_id"], ["masjids.masjid_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "masjid_id"),
        sa.UniqueConstraint("user_id", "masjid_id", name="uq_user_masjid_follow"),
    )
    op.create_index(
        op.f("ix_user_masjid_follows_masjid_id"),
        "user_masjid_follows",
        ["masjid_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_masjid_follows_masjid_id"), table_name="user_masjid_follows"
    )
    op.drop_table("user_masjid_follows")
    # ### end Alembic commands ###
