"""add_audit_logs_and_announcements

Revision ID: 26bd9b9f5030
Revises: cd75bf5660ea
Create Date: 2026-04-16 00:33:50.845080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26bd9b9f5030'
down_revision: Union[str, Sequence[str], None] = 'cd75bf5660ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('admin_email', sa.String(length=255), nullable=True),
    sa.Column('admin_role', sa.String(length=30), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target_entity', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_table('announcements',
    sa.Column('announcement_id', sa.UUID(), nullable=False),
    sa.Column('masjid_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('posted_by_id', sa.UUID(), nullable=False),
    sa.Column('posted_by_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['masjid_id'], ['masjids.masjid_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('announcement_id')
    )
    op.create_index(op.f('ix_announcements_masjid_id'), 'announcements', ['masjid_id'], unique=False)
    # Composite index for fast public feed queries (masjid + published)
    op.create_index('ix_announcements_masjid_published', 'announcements', ['masjid_id', 'is_published'])
    # idx_masjids_location and idx_masjids_status_created managed by c317cc918abb — do NOT drop
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_announcements_masjid_published', table_name='announcements')
    op.drop_index(op.f('ix_announcements_masjid_id'), table_name='announcements')
    op.drop_table('announcements')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
