"""add_prd05_donation_system

Revision ID: 2fb604ddb042
Revises: edc8042ef40b
Create Date: 2026-06-20 15:38:36.627513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fb604ddb042'
down_revision: Union[str, Sequence[str], None] = 'edc8042ef40b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donation_receipt_counters',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('last_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('year')
    )
    op.create_table('disbursements',
    sa.Column('disbursement_id', sa.UUID(), nullable=False),
    sa.Column('masjid_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('disbursed_on', sa.Date(), nullable=False),
    sa.Column('recorded_by_id', sa.UUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("method IN ('bank','bkash','cash')", name='ck_disbursements_method'),
    sa.CheckConstraint('amount > 0', name='ck_disbursements_amount_positive'),
    sa.ForeignKeyConstraint(['masjid_id'], ['masjids.masjid_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('disbursement_id')
    )
    op.create_index(op.f('ix_disbursements_masjid_id'), 'disbursements', ['masjid_id'], unique=False)
    op.create_table('donations',
    sa.Column('donation_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('masjid_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('donor_name', sa.String(length=255), nullable=True),
    sa.Column('donor_email', sa.String(length=255), nullable=True),
    sa.Column('gateway_session_key', sa.Text(), nullable=True),
    sa.Column('gateway_val_id', sa.String(length=255), nullable=True),
    sa.Column('gateway_bank_tran_id', sa.String(length=255), nullable=True),
    sa.Column('gateway_payment_method', sa.String(length=50), nullable=True),
    sa.Column('receipt_number', sa.String(length=30), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(category = 'campaign') = (campaign_id IS NOT NULL)", name='ck_donations_campaign_category'),
    sa.CheckConstraint("category IN ('general','building','zakat','sadaqah','lillah','campaign')", name='ck_donations_category'),
    sa.CheckConstraint("status IN ('pending','completed','refunded','failed')", name='ck_donations_status'),
    sa.CheckConstraint('gross_amount >= 10 AND gross_amount <= 500000', name='ck_donations_gross_bounds'),
    sa.CheckConstraint('net_amount = gross_amount - fee_amount', name='ck_donations_net_arithmetic'),
    sa.ForeignKeyConstraint(['campaign_id'], ['masjid_campaigns.campaign_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['masjid_id'], ['masjids.masjid_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('donation_id'),
    sa.UniqueConstraint('gateway_val_id'),
    sa.UniqueConstraint('receipt_number')
    )
    op.create_index('ix_donations_campaign', 'donations', ['campaign_id'], unique=False, postgresql_where=sa.text('campaign_id IS NOT NULL'))
    op.create_index('ix_donations_masjid_status', 'donations', ['masjid_id', 'status'], unique=False)
    op.create_index('ix_donations_status_created', 'donations', ['status', 'created_at'], unique=False)
    op.create_index('ix_donations_user_created', 'donations', ['user_id', 'created_at'], unique=False)
    op.create_table('recurring_schedules',
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('masjid_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('frequency', sa.String(length=10), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('next_due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(category = 'campaign') = (campaign_id IS NOT NULL)", name='ck_recurring_campaign_category'),
    sa.CheckConstraint("category IN ('general','building','zakat','sadaqah','lillah','campaign')", name='ck_recurring_category'),
    sa.CheckConstraint("frequency IN ('weekly','monthly','nightly')", name='ck_recurring_frequency'),
    sa.CheckConstraint("status IN ('active','paused','cancelled')", name='ck_recurring_status'),
    sa.CheckConstraint('amount >= 10 AND amount <= 500000', name='ck_recurring_amount_bounds'),
    sa.ForeignKeyConstraint(['campaign_id'], ['masjid_campaigns.campaign_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['masjid_id'], ['masjids.masjid_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('schedule_id')
    )
    op.create_index('ix_recurring_due', 'recurring_schedules', ['next_due_at', 'status'], unique=False)
    op.create_index(op.f('ix_recurring_schedules_masjid_id'), 'recurring_schedules', ['masjid_id'], unique=False)
    op.create_index('ix_recurring_user', 'recurring_schedules', ['user_id'], unique=False)
    # PRD 05 — NBR tax-deductibility flag; default false seeds the existing
    # singleton row and keeps new receipts from making a false legal claim.
    op.add_column(
        'platform_settings',
        sa.Column(
            'tax_deductible_receipts_enabled',
            sa.Boolean(),
            nullable=False,
            server_default=sa.text('false'),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platform_settings', 'tax_deductible_receipts_enabled')
    op.drop_index('ix_recurring_user', table_name='recurring_schedules')
    op.drop_index(op.f('ix_recurring_schedules_masjid_id'), table_name='recurring_schedules')
    op.drop_index('ix_recurring_due', table_name='recurring_schedules')
    op.drop_table('recurring_schedules')
    op.drop_index('ix_donations_user_created', table_name='donations')
    op.drop_index('ix_donations_status_created', table_name='donations')
    op.drop_index('ix_donations_masjid_status', table_name='donations')
    op.drop_index('ix_donations_campaign', table_name='donations', postgresql_where=sa.text('campaign_id IS NOT NULL'))
    op.drop_table('donations')
    op.drop_index(op.f('ix_disbursements_masjid_id'), table_name='disbursements')
    op.drop_table('disbursements')
    op.drop_table('donation_receipt_counters')
    # ### end Alembic commands ###
