"""add_support_tickets

Revision ID: 71fd965b780b
Revises: 9dcb32c2e860
Create Date: 2026-04-25 20:46:15.577556

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "71fd965b780b"
down_revision: Union[str, Sequence[str], None] = "9dcb32c2e860"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "support_tickets",
        sa.Column("ticket_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("user_email", sa.String(length=255), nullable=True),
        sa.Column("category", sa.String(length=30), nullable=False),
        sa.Column("subject", sa.String(length=200), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status", sa.String(length=20), server_default="Open", nullable=False
        ),
        sa.Column("assigned_to", sa.UUID(), nullable=True),
        sa.Column("assigned_to_email", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "category IN ('Bug','IncorrectData','FeatureRequest','Other')",
            name="ck_support_tickets_category",
        ),
        sa.CheckConstraint(
            "status IN ('Open','InProgress','Resolved')",
            name="ck_support_tickets_status",
        ),
        sa.PrimaryKeyConstraint("ticket_id"),
    )
    op.create_index(
        "idx_support_tickets_created_at",
        "support_tickets",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "idx_support_tickets_status", "support_tickets", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_support_tickets_status", table_name="support_tickets")
    op.drop_index("idx_support_tickets_created_at", table_name="support_tickets")
    op.drop_table("support_tickets")
    # ### end Alembic commands ###
