"""add_masjid_events

Revision ID: 7b683a61a51b
Revises: 2535dc4d3f25
Create Date: 2026-04-25 19:47:37.043076

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7b683a61a51b"
down_revision: Union[str, Sequence[str], None] = "2535dc4d3f25"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "masjid_events",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("masjid_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("event_date", sa.Date(), nullable=False),
        sa.Column("event_time", sa.Time(), nullable=False),
        sa.Column("location", sa.String(length=300), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=True),
        sa.Column("rsvp_enabled", sa.Boolean(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.Column("created_by_email", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["masjid_id"], ["masjids.masjid_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(
        "idx_masjid_events_masjid_date",
        "masjid_events",
        ["masjid_id", "event_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_masjid_events_masjid_id"), "masjid_events", ["masjid_id"], unique=False
    )
    op.create_table(
        "event_rsvps",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "rsvp_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["masjid_events.event_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("event_id", "user_id"),
    )
    op.create_index(
        op.f("ix_event_rsvps_event_id"), "event_rsvps", ["event_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_event_rsvps_event_id"), table_name="event_rsvps")
    op.drop_table("event_rsvps")
    op.drop_index(op.f("ix_masjid_events_masjid_id"), table_name="masjid_events")
    op.drop_index("idx_masjid_events_masjid_date", table_name="masjid_events")
    op.drop_table("masjid_events")
    # ### end Alembic commands ###
