"""add_masjid_reports_and_audit_details

Revision ID: 9ac5759232e8
Revises: 26bd9b9f5030
Create Date: 2026-04-25 18:36:48.591193

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9ac5759232e8"
down_revision: Union[str, Sequence[str], None] = "26bd9b9f5030"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "masjid_reports",
        sa.Column("report_id", sa.UUID(), nullable=False),
        sa.Column("masjid_id", sa.UUID(), nullable=True),
        sa.Column("field_name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("reporter_email", sa.String(length=255), nullable=True),
        sa.Column(
            "status", sa.String(length=20), server_default="pending", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending','reviewed','resolved')",
            name="ck_masjid_reports_status",
        ),
        sa.ForeignKeyConstraint(
            ["masjid_id"], ["masjids.masjid_id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("report_id"),
    )
    op.create_index(
        op.f("ix_masjid_reports_created_at"),
        "masjid_reports",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_masjid_reports_masjid_id"),
        "masjid_reports",
        ["masjid_id"],
        unique=False,
    )
    op.add_column(
        "audit_logs",
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("audit_logs", "details")
    op.drop_index(op.f("ix_masjid_reports_masjid_id"), table_name="masjid_reports")
    op.drop_index(op.f("ix_masjid_reports_created_at"), table_name="masjid_reports")
    op.drop_table("masjid_reports")
    # ### end Alembic commands ###
