"""add_masjid_campaigns

Revision ID: 9dcb32c2e860
Revises: 05e64234de03
Create Date: 2026-04-25 20:39:17.538015

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9dcb32c2e860"
down_revision: Union[str, Sequence[str], None] = "05e64234de03"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "masjid_campaigns",
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column("masjid_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("target_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("raised_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("banner_url", sa.Text(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default="Active", nullable=False
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.Column("created_by_email", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('Active','Completed','Cancelled')", name="ck_campaigns_status"
        ),
        sa.CheckConstraint("end_date >= start_date", name="ck_campaigns_date_range"),
        sa.CheckConstraint("target_amount > 0", name="ck_campaigns_target_positive"),
        sa.ForeignKeyConstraint(
            ["masjid_id"], ["masjids.masjid_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("campaign_id"),
    )
    op.create_index(
        "idx_campaigns_masjid_status",
        "masjid_campaigns",
        ["masjid_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_masjid_campaigns_masjid_id"),
        "masjid_campaigns",
        ["masjid_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_masjid_campaigns_masjid_id"), table_name="masjid_campaigns")
    op.drop_index("idx_campaigns_masjid_status", table_name="masjid_campaigns")
    op.drop_table("masjid_campaigns")
    # ### end Alembic commands ###
