"""create_masjid_tables

Revision ID: c317cc918abb
Revises: df147ef6544b
Create Date: 2026-04-15 23:02:40.695948

"""

from typing import Sequence, Union

import geoalchemy2
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c317cc918abb"
down_revision: Union[str, Sequence[str], None] = "df147ef6544b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "masjids",
        sa.Column("masjid_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column("admin_region", sa.String(length=100), nullable=False),
        sa.Column(
            "location",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeogFromText",
                name="geography",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("donations_enabled", sa.Boolean(), nullable=False),
        sa.Column("timezone", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("suspension_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending','active','suspended','removed')",
            name="ck_masjids_status",
        ),
        sa.PrimaryKeyConstraint("masjid_id"),
    )
    op.create_table(
        "masjid_contact",
        sa.Column("masjid_id", sa.UUID(), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("whatsapp", sa.String(length=20), nullable=True),
        sa.Column("website_url", sa.Text(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["masjid_id"], ["masjids.masjid_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("masjid_id"),
    )
    op.create_table(
        "masjid_facilities",
        sa.Column("masjid_id", sa.UUID(), nullable=False),
        sa.Column("has_sisters_section", sa.Boolean(), nullable=False),
        sa.Column("has_wudu_area", sa.Boolean(), nullable=False),
        sa.Column("has_wudu_male", sa.Boolean(), nullable=False),
        sa.Column("has_wudu_female", sa.Boolean(), nullable=False),
        sa.Column("has_wheelchair_access", sa.Boolean(), nullable=False),
        sa.Column("has_parking", sa.Boolean(), nullable=False),
        sa.Column("parking_capacity", sa.Integer(), nullable=True),
        sa.Column("has_janazah", sa.Boolean(), nullable=False),
        sa.Column("has_school", sa.Boolean(), nullable=False),
        sa.Column("imam_name", sa.String(length=200), nullable=True),
        sa.Column("imam_qualifications", sa.Text(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["masjid_id"], ["masjids.masjid_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("masjid_id"),
    )
    op.create_table(
        "masjid_photos",
        sa.Column("photo_id", sa.UUID(), nullable=False),
        sa.Column("masjid_id", sa.UUID(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("is_cover", sa.Boolean(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["masjid_id"], ["masjids.masjid_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("photo_id"),
    )
    # GIST spatial index — hand-added; autogenerate skips this because spatial_index=False
    op.create_index(
        "idx_masjids_location", "masjids", ["location"], postgresql_using="gist"
    )
    op.create_index("idx_masjids_status_created", "masjids", ["status", "created_at"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_masjids_status_created", table_name="masjids")
    op.drop_index("idx_masjids_location", table_name="masjids", postgresql_using="gist")
    op.drop_table("masjid_photos")
    op.drop_table("masjid_facilities")
    op.drop_table("masjid_contact")
    op.drop_table("masjids")
    # ### end Alembic commands ###
