"""add_prayer_times_and_jumah

Revision ID: cd75bf5660ea
Revises: c317cc918abb
Create Date: 2026-04-16 00:06:21.169165

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cd75bf5660ea"
down_revision: Union[str, Sequence[str], None] = "c317cc918abb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jumah_schedules",
        sa.Column("masjid_id", sa.UUID(), nullable=False),
        sa.Column("khutbah_1_azan", sa.Time(), nullable=True),
        sa.Column("khutbah_1_start", sa.Time(), nullable=True),
        sa.Column("khutbah_2_azan", sa.Time(), nullable=True),
        sa.Column("khutbah_2_start", sa.Time(), nullable=True),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["masjid_id"], ["masjids.masjid_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("masjid_id"),
    )
    op.create_table(
        "prayer_times",
        sa.Column("prayer_time_id", sa.UUID(), nullable=False),
        sa.Column("masjid_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("fajr_azan", sa.Time(), nullable=False),
        sa.Column("dhuhr_azan", sa.Time(), nullable=False),
        sa.Column("asr_azan", sa.Time(), nullable=False),
        sa.Column("maghrib_azan", sa.Time(), nullable=False),
        sa.Column("isha_azan", sa.Time(), nullable=False),
        sa.Column("fajr_iqamah", sa.Time(), nullable=True),
        sa.Column("dhuhr_iqamah", sa.Time(), nullable=True),
        sa.Column("asr_iqamah", sa.Time(), nullable=True),
        sa.Column("maghrib_iqamah", sa.Time(), nullable=True),
        sa.Column("isha_iqamah", sa.Time(), nullable=True),
        sa.Column("is_manual", sa.Boolean(), nullable=False),
        sa.Column("calculation_method", sa.String(length=40), nullable=False),
        sa.Column("madhab", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["masjid_id"], ["masjids.masjid_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("prayer_time_id"),
        sa.UniqueConstraint("masjid_id", "date", name="uq_prayer_times_masjid_date"),
    )
    op.create_index(
        op.f("ix_prayer_times_masjid_id"), "prayer_times", ["masjid_id"], unique=False
    )
    # Note: idx_masjids_location and idx_masjids_status_created are managed by
    # migration c317cc918abb — do NOT drop them here.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_prayer_times_masjid_id"), table_name="prayer_times")
    op.drop_table("prayer_times")
    op.drop_table("jumah_schedules")
    # ### end Alembic commands ###
