"""add_gamification_tables

Revision ID: e327fed93317
Revises: fb51dc5bacd4
Create Date: 2026-04-25 21:12:56.733863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e327fed93317'
down_revision: Union[str, Sequence[str], None] = 'fb51dc5bacd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_badges',
    sa.Column('badge_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('badge_type', sa.String(length=30), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("badge_type IN ('FajrWarrior','GenerousGiver','CommunityPillar')", name='ck_user_badges_type'),
    sa.PrimaryKeyConstraint('badge_id'),
    sa.UniqueConstraint('user_id', 'badge_type', name='uq_user_badge_type')
    )
    op.create_index('idx_user_badges_user', 'user_badges', ['user_id'], unique=False)
    op.create_table('user_journal_entries',
    sa.Column('journal_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('prayers_logged', sa.Text(), nullable=True),
    sa.Column('quran_pages', sa.SmallInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('journal_id'),
    sa.UniqueConstraint('user_id', 'entry_date', name='uq_journal_user_date')
    )
    op.create_index('idx_journal_user_date', 'user_journal_entries', ['user_id', 'entry_date'], unique=False)
    op.create_table('user_checkins',
    sa.Column('checkin_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('masjid_id', sa.UUID(), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['masjid_id'], ['masjids.masjid_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('checkin_id')
    )
    op.create_index('idx_checkins_user_date', 'user_checkins', ['user_id', 'checked_in_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_checkins_user_date', table_name='user_checkins')
    op.drop_table('user_checkins')
    op.drop_index('idx_journal_user_date', table_name='user_journal_entries')
    op.drop_table('user_journal_entries')
    op.drop_index('idx_user_badges_user', table_name='user_badges')
    op.drop_table('user_badges')
    # ### end Alembic commands ###
