"""add_backend_gaps

Revision ID: f0da157c7611
Revises: e327fed93317
Create Date: 2026-04-25 21:38:18.739527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0da157c7611'
down_revision: Union[str, Sequence[str], None] = 'e327fed93317'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_settings',
    sa.Column('settings_id', sa.UUID(), nullable=False),
    sa.Column('default_madhab', sa.String(length=20), nullable=False),
    sa.Column('default_calc_method', sa.String(length=30), nullable=False),
    sa.Column('supported_countries', postgresql.ARRAY(sa.String(length=2)), nullable=True),
    sa.Column('reviews_enabled', sa.Boolean(), nullable=False),
    sa.Column('checkins_enabled', sa.Boolean(), nullable=False),
    sa.Column('platform_name', sa.String(length=100), nullable=False),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=False),
    sa.Column('maintenance_message', sa.Text(), nullable=True),
    sa.Column('terms_of_service', sa.Text(), nullable=True),
    sa.Column('privacy_policy', sa.Text(), nullable=True),
    sa.Column('terms_version', sa.String(length=20), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by_email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('settings_id')
    )
    op.add_column('masjid_facilities', sa.Column('imam_languages', sa.String(length=200), nullable=True))
    op.add_column('masjid_facilities', sa.Column('capacity_male', sa.SmallInteger(), nullable=True))
    op.add_column('masjid_facilities', sa.Column('capacity_female', sa.SmallInteger(), nullable=True))
    op.add_column('user_profiles', sa.Column('is_suspended', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('user_profiles', sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_profiles', sa.Column('suspension_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'suspension_reason')
    op.drop_column('user_profiles', 'suspended_at')
    op.drop_column('user_profiles', 'is_suspended')
    op.drop_column('masjid_facilities', 'capacity_female')
    op.drop_column('masjid_facilities', 'capacity_male')
    op.drop_column('masjid_facilities', 'imam_languages')
    op.drop_table('platform_settings')
    # ### end Alembic commands ###
