"""add_masjid_co_admin_invites

Revision ID: fb51dc5bacd4
Revises: 71fd965b780b
Create Date: 2026-04-25 21:00:09.602337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb51dc5bacd4'
down_revision: Union[str, Sequence[str], None] = '71fd965b780b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('masjid_co_admin_invites',
    sa.Column('invite_id', sa.UUID(), nullable=False),
    sa.Column('masjid_id', sa.UUID(), nullable=False),
    sa.Column('invited_email', sa.String(length=255), nullable=False),
    sa.Column('invited_by_id', sa.UUID(), nullable=False),
    sa.Column('invited_by_email', sa.String(length=255), nullable=True),
    sa.Column('gotrue_user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='Pending', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resend_count', sa.Integer(), nullable=False),
    sa.Column('last_resent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('Pending','Accepted','Declined','Revoked','Expired')", name='ck_co_admin_invites_status'),
    sa.ForeignKeyConstraint(['masjid_id'], ['masjids.masjid_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('invite_id')
    )
    op.create_index('idx_co_admin_invites_gotrue_user', 'masjid_co_admin_invites', ['gotrue_user_id'], unique=False)
    op.create_index('idx_co_admin_invites_masjid', 'masjid_co_admin_invites', ['masjid_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_co_admin_invites_masjid', table_name='masjid_co_admin_invites')
    op.drop_index('idx_co_admin_invites_gotrue_user', table_name='masjid_co_admin_invites')
    op.drop_table('masjid_co_admin_invites')
    # ### end Alembic commands ###
