"""Raw bulk statements for the 30-day account-deletion purge (PRD 09 #1).

Anonymisation, not deletion: every soft-deleted account's content rows are kept
(aggregates survive) but their identity is severed. Because users live in
GoTrue, every table carries a *bare* ``user_id`` UUID with no FK, so a single
``UPDATE … SET user_id = <pseudonym>`` per table re-keys the rows. The pseudonym
is a fresh per-user ``uuid4`` generated by the service, so the 1-to-1 remap can
never collide on any composite/unique constraint that includes ``user_id``
(follows PK, RSVP PK, ``user_badges``/``user_journal_entries`` uniqueness, the
review upsert) — no per-table special-casing needed.

Two carve-outs are hard-deleted rather than remapped, because keeping them would
actively harm the ex-user: ``device_tokens`` (would keep delivering pushes to a
device that no longer belongs to anyone) and ``recurring_schedules`` (would keep
nudging toward a recurring gift). Admin-authored rows (announcements, events,
campaigns, co-admin invites, audit logs) are out of scope — they are not consumer
data and anonymising them would damage audit trails.
"""

import uuid
from datetime import datetime

from sqlalchemy import delete, select, update

from app.models.device_token import DeviceToken
from app.models.donation import Donation
from app.models.masjid import MasjidPhoto
from app.models.masjid_event import EventRsvp
from app.models.masjid_question import MasjidQuestion
from app.models.masjid_report import MasjidReport
from app.models.masjid_review import MasjidReview
from app.models.masjid_submission import MasjidSubmission
from app.models.recurring_schedule import RecurringSchedule
from app.models.support_ticket import SupportTicket
from app.models.user_badge import UserBadge
from app.models.user_checkin import UserCheckin
from app.models.user_goal import UserGoal
from app.models.user_journal_entry import UserJournalEntry
from app.models.user_masjid_follow import UserMasjidFollow
from app.models.user_profile import UserProfile
from app.repositories.base import BaseRepository

# (model, identity-column name) — every content table that carries the bare
# user UUID. Re-keyed to the pseudonym; rows are kept.
_REMAP_TABLES: list[tuple[type, str]] = [
    (MasjidReview, "user_id"),
    (MasjidQuestion, "asker_user_id"),
    (MasjidSubmission, "user_id"),
    (UserCheckin, "user_id"),
    (UserJournalEntry, "user_id"),
    (UserGoal, "user_id"),
    (UserBadge, "user_id"),
    (SupportTicket, "user_id"),
    (MasjidReport, "user_id"),
    (UserMasjidFollow, "user_id"),
    (EventRsvp, "user_id"),
    (MasjidPhoto, "uploaded_by"),
]

# (model, identity-column name) — hard-deleted, never remapped (see module docstring).
_DELETE_TABLES: list[tuple[type, str]] = [
    (DeviceToken, "user_id"),
    (RecurringSchedule, "user_id"),
]

# Remapped tables that ALSO carry a direct-PII *snapshot* of the user's identity
# (copied from the profile/GoTrue at write time), which re-keying alone leaves
# behind. These columns are nulled in the same UPDATE so the row's aggregate
# survives but the person is no longer identifiable — e.g. a public review keeps
# its stars/body but loses the reviewer's real name, and a support ticket keeps
# its category/description but loses the login email. Free-text the user authored
# (review body, ticket subject/description) is content, not an identity snapshot,
# so it is deliberately kept (mirrors the Donation carve-out below).
_REMAP_BLANK_PII: dict[type, tuple[str, ...]] = {
    MasjidReview: ("reviewer_display_name",),
    SupportTicket: ("user_email",),
}


class AccountPurgeRepository(BaseRepository[UserProfile]):
    model = UserProfile

    async def find_due(self, cutoff: datetime, limit: int) -> list[UserProfile]:
        """Soft-deleted profiles whose 30-day window has elapsed and that have
        not yet been purged. ``purged_at`` is the idempotency gate."""
        result = await self.db.execute(
            select(UserProfile)
            .where(
                UserProfile.is_deleted.is_(True),
                UserProfile.deletion_requested_at.is_not(None),
                UserProfile.deletion_requested_at < cutoff,
                UserProfile.purged_at.is_(None),
            )
            .order_by(UserProfile.deletion_requested_at)
            .limit(limit)
        )
        return list(result.scalars().all())

    async def anonymize_user(self, real_id: uuid.UUID, pseudonym: uuid.UUID) -> None:
        """Re-key every content row from ``real_id`` to ``pseudonym`` and blank
        direct-PII contact fields; hard-delete the two carve-out tables. Flushes;
        the service commits."""
        # Donations also blank the donor name/email snapshot — the row (and its
        # gapless receipt number, keyed by donation_id) survives for the masjid's
        # books, but the donor is no longer identifiable.
        await self.db.execute(
            update(Donation)
            .where(Donation.user_id == real_id)
            .values(user_id=pseudonym, donor_name=None, donor_email=None)
        )
        for model, column in _REMAP_TABLES:
            # Re-key the identity UUID and, for tables that snapshot direct PII,
            # null those columns in the same statement (see _REMAP_BLANK_PII).
            pii_blanks = {c: None for c in _REMAP_BLANK_PII.get(model, ())}
            await self.db.execute(
                update(model)
                .where(getattr(model, column) == real_id)
                .values(**{column: pseudonym}, **pii_blanks)
            )
        for model, column in _DELETE_TABLES:
            await self.db.execute(
                delete(model).where(getattr(model, column) == real_id)
            )
        await self.db.flush()

    async def mark_purged(self, profile: UserProfile, when: datetime) -> None:
        """Reduce the profile to a stripped tombstone under its ORIGINAL user_id
        (kept so the /users/me 410-gone guard still fires) and stamp purged_at."""
        profile.display_name = None
        profile.madhab = None
        profile.profile_photo_url = None
        profile.purged_at = when
        await self.db.flush()
